### ISSUE TITLE
Add scanning to pipeline

### ISSUE THREAD

**Issue by isym444** [isym444/pyqtTodo#37]
?veracode ?sonarqube

**Comment by Benjamin-taro** [comment]
I looked up and setup sonarqube to add scanning to pipeline, but it seems like this is only allowed to the owner of the repository.
Steps to setup sonarqube
1. download the community edition of sonarqube from this [https://www.sonarsource.com/products/sonarqube/downloads/?s_campaign=SQ-EMEA-North-UKI-Brand&s_content=Languages&s_term=sonar%20java&s_category=Paid&s_source=Paid%20Search&s_origin=Google&cq_src=google_ads&cq_cmp=21484226150&cq_con=161812572381&cq_term=sonar%20java&cq_med=&cq_plac=&cq_net=g&cq_pos=&cq_plt=gp&gad_source=1&gclid=CjwKCAjwpbi4BhByEiwAMC8JnSKZUwTcyz2bGurZ0NNSzTQTfs2Ke8OR9l2-hYQLa1Fe6YdFJFuoqxoC0eQQAvD_BwE](url)
2. unzip the folder and move to this directory
3. run this command "./bin/macosx-universal-64/sonar.sh start"
4. then access to http://localhost:9000/
5. You will be asked to type ID and password, so type "admin" for both.
6. after the login, you have to change the password.
7. Connect to your GitHub account and fill in the blanks to create the configuration.

**Comment by isym444** [comment]
Added CodeQL scanning
![image](https://github.com/user-attachments/assets/a683791f-0890-4729-a851-fe504564cf61)
